"""AutoPwn shell verification helper (P11.6 / v4.0.1).

Per ``upgraded.md`` §3.1 v4.0.1: replace the v3.1 ``io.interactive()``
success signal with a real shell-availability probe.  The
prior behavior (still preserved as a banner in v3.1) was::

    print_critical("EXPLOITATION SUCCESSFUL! Dropping to shell...")
    io.interactive()   # blocks waiting for stdin; in run_verify.sh
                       # (no stdin) this raises immediately

That made every primitive report SUCCESS even when the spawned
process died before ``system("/bin/sh")`` could run.  This
module replaces that signal with a 2-second ``echo PWNED``
probe (v4.0.4, was ``id`` in v4.0.1 — Owner 2026-06-11 refined
to ``echo PWNED`` because ``id`` is not guaranteed on minimal
shells like busybox/dash)::

    >>> io = process(program)
    >>> io.sendline(payload)
    >>> ok, verify_output = verify_shell(io, timeout=2.0)
    >>> if ok:
    ...     print("real shell acquired; verify output: " + verify_output.strip())
    ... else:
    ...     print("exploit failed; no PWNED in output")

Design notes
------------
* The function takes a pwntools tube (``io``) — it is agnostic to
  whether the tube is a local ``process`` or a ``remote``.  This
  keeps the helper usable from any strategy.
* The helper swallows all pwntools errors (EOFError, OSError) and
  returns ``(False, "")``.  Callers MUST check the boolean — never
  infer success from a non-empty ``verify_output`` (an attacker
  can echo ``PWNED`` to a dead shell before the timeout).
* The timeout default (2.0s) is intentionally short — successful
  ``system("/bin/sh")`` + ``echo PWNED`` should complete in < 50ms;
  the extra headroom tolerates scheduler jitter.  Longer timeouts
  make ``run_verify.sh`` slow without adding real signal.
* **Silent success** (v4.0.4+): this module no longer prints the
  ``EXPLOITATION SUCCESSFUL! Dropping to shell...`` banner.  The
  only visible success signal is the docx report generated by
  :func:`record_success` + the verifier output stamped on
  ``info.id_output`` and ``ctx.id_output``.
* **Probe/spec core** (v5.0.9): `verify_with_probe` centralizes the
  command / token / parse flow, while compatibility wrappers keep the
  existing public API stable.
"""
from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any, Callable, Optional, Tuple


# v4.0.4: the unique verify string.  Hard-coded so all strategies
# and the docx report use the exact same canonical token.
_VERIFY_COMMAND = b"echo PWNED"
_VERIFY_TOKEN = b"PWNED"
_WHOAMI_COMMAND = b"whoami; echo __AUTOPWN_END__"
_WHOAMI_TOKEN = b"__AUTOPWN_END__"
_WHOAMI_LINE_RE = re.compile(rb"^[A-Za-z0-9_.-]+$")


@dataclass(frozen=True, slots=True)
class VerifyProbe:
    name: str
    command: bytes
    token: bytes
    parse_output: Callable[[Any, bytes, float], Optional[str]]


def _drain_banner(io) -> None:
    try:
        io.recv(timeout=0.1)
    except Exception:
        pass


def _parse_echo_pwned(io, _matched: bytes, timeout: float) -> Optional[str]:
    try:
        line = io.recvline(timeout=timeout)
    except Exception:
        return None
    if not line:
        return None
    return (_VERIFY_TOKEN + line).decode(errors="replace")


def _parse_whoami(_io, matched: bytes, _timeout: float) -> Optional[str]:
    for raw_line in matched.splitlines():
        line = raw_line.strip()
        if not line or line == _WHOAMI_TOKEN:
            continue
        if _WHOAMI_LINE_RE.fullmatch(line):
            return line.decode(errors="replace") + "\n"
    return None


PWNED_PROBE = VerifyProbe(
    name="echo_pwned",
    command=_VERIFY_COMMAND,
    token=_VERIFY_TOKEN,
    parse_output=_parse_echo_pwned,
)

WHOAMI_PROBE = VerifyProbe(
    name="whoami",
    command=_WHOAMI_COMMAND,
    token=_WHOAMI_TOKEN,
    parse_output=_parse_whoami,
)


def verify_with_probe(
    io, probe: VerifyProbe, timeout: float = 2.0, *, keep_alive: bool = False,
) -> Tuple[bool, str]:
    try:
        _drain_banner(io)
        io.sendline(probe.command)
        try:
            matched = io.recvuntil(probe.token, timeout=timeout)
        except Exception:
            return (False, "")
        verify_output = probe.parse_output(io, matched, timeout)
        if not verify_output:
            return (False, "")
        return (True, verify_output)
    except Exception:
        return (False, "")
    finally:
        if not keep_alive:
            try:
                io.close()
            except Exception:
                pass


def verify_shell(
    io, timeout: float = 2.0, *, keep_alive: bool = False,
) -> Tuple[bool, str]:
    """Probe whether ``io`` has a real shell by sending ``echo PWNED``."""
    return verify_with_probe(io, PWNED_PROBE, timeout=timeout, keep_alive=keep_alive)


def verify_shell_whoami(
    io, timeout: float = 2.0, *, keep_alive: bool = False,
) -> Tuple[bool, str]:
    """Probe whether ``io`` has a real shell by executing ``whoami``."""
    return verify_with_probe(io, WHOAMI_PROBE, timeout=timeout, keep_alive=keep_alive)


__all__ = [
    "VerifyProbe",
    "verify_with_probe",
    "verify_shell",
    "verify_shell_whoami",
]


def record_success_verified(
    info: "ExploitInfo",
    verify_ok: bool,
    verify_output: str,
    ctx: "ExploitContext | None" = None,
) -> bool:
    """Dispatch to ``record_success`` only when verify_shell confirmed
    a real shell.  Silent — no banner print (v4.0.4).

    Per ``upgraded.md`` §3.1 v4.0.4 — the v4.0.3 fix moved the
    ``EXPLOITATION SUCCESSFUL`` banner to after verify_shell, but
    the banner itself was still printed.  v4.0.4 removes the
    banner entirely: the **sole visible success signal** is the
    docx report generated by :func:`record_success` + the
    ``verify_output`` string stamped on ``info.id_output`` and
    ``ctx.id_output``.

    Variable naming note (v4.0.4+): the historical ``id_ok`` /
    ``id_output`` parameter names have been renamed to
    ``verify_ok`` / ``verify_output`` to reflect generic shell
    verification. Existing strategy call sites
    (``verify_shell(io) → record_success_verified(info, ok, out, ctx)``)
    pass positional args, so no caller update is required.

    Usage pattern (replaces the v4.0.1 boilerplate in every
    strategy's ``run`` method)::

        verify_ok, verify_output = verify_shell(io)
        ok = record_success_verified(info, verify_ok, verify_output, ctx)
        if not ok:
            print_warning(f"{self.__class__.__name__}: shell verification failed")
            return False
        ctx.id_output = verify_output
        return True

    Returns:
        ``True`` iff ``verify_ok`` is True (real shell acquired) —
        the caller should also ``return True`` from ``strategy.run``.

    Side effects (only when ``verify_ok`` is True):
        * Calls :func:`autopwn.report.record_success` to generate
          the docx / md report.
        * Stamps ``info.id_output`` and ``ctx.id_output`` with the
          verifier output (e.g. ``"PWNED\\n"`` or ``"root\\n"``).

    No stdout / stderr output by this function (v4.0.4 silent path).
    """
    if not verify_ok:
        # No banner, no report — exploit did not actually yield a
        # shell.  Caller should ``return False`` from ``run``.
        return False

    # Real success path — silent (no banner print per v4.0.4).
    # The verify_output is the only in-band success payload; the
    # docx report is the persistent success artifact.
    info.id_output = verify_output
    if ctx is not None:
        ctx.id_output = verify_output

    from autopwn.report import record_success
    record_success(info)

    return True


__all__ = [
    "VerifyProbe",
    "verify_with_probe",
    "verify_shell",
    "verify_shell_whoami",
    "record_success_verified",
]
